### ISSUE TITLE
Do you know the password of the ZIP file 'breasthistology' dataset?

### ISSUE THREAD

**Issue by wang66624** [jancio/Patch-based-Classification-of-Breast-Cancer-Histology-Images-using-CNNs#1]
![image](https://user-images.githubusercontent.com/81811919/176994715-c84de651-5499-4316-a79d-ff5eeda42550.png)

**Comment by DemoAllan** [comment]
> 

请问您知道密码了吗？希望告知

**Comment by jancio** [comment]
Please request the password from the dataset creators/maintainers.

**Comment by DemoAllan** [comment]
> 

Thank you for your kindly reply~
